language: php

php:
  - 7.2
  - 7.3
  - 7.4

sudo: false

git:
 depth: 10000

before_install:
  - phpenv config-rm xdebug.ini
  - composer --verbose self-update --2
  - composer --version

install:
  - composer --verbose install

before_script:
  - git config --global user.email "travisci@example.com"
  - git config --global user.name "Travis CI Test"

script:
  - ./vendor/bin/phpunit
